
db.averages.updateMany({title: 'Tecnología de los Materiales I'}, {$set:{codigo:"CATMA107"}})
db.averages.updateMany({title: 'Fotografía Artística I'}, {$set:{codigo:"CAFOR309"}})
db.averages.updateMany({title: 'Morfología Visual I'}, {$set:{codigo:"CAMVI111"}})
db.averages.updateMany({title: 'Comunicación Visual'}, {$set:{codigo:"CACVI205"}})
db.averages.updateMany({title: 'Comunicación I'}, {$set:{codigo:"FGCOM101"}})
db.averages.updateMany({title: 'Dibujo I'},  {$set:{codigo:"FEDIB115"}})
db.averages.updateMany({title: 'Historia del Arte II'}, {$set:{codigo:"CAHAR207"}})
db.averages.updateMany({title: 'Taller Principal V (PEG)'}, {$set:{codigo:"FETAP311"}})
db.averages.updateMany({title: 'Dibujo III'},  {$set:{codigo:"FEDIB215"}})
db.averages.updateMany({title: 'Geometría Descriptiva I'}, {$set:{codigo:"CAGDE211"}})
db.averages.updateMany({title: 'Anatomía Artística II'}, {$set:{codigo:"CAAAR303"}})
db.averages.updateMany({title: 'Investigación Artística III'}, {$set:{codigo:"FEINA507"}})
db.averages.updateMany({title: 'Matemática Aplicada al Arte'}, {$set:{codigo:"FGMAA103"}})
db.averages.updateMany({title: 'Dibujo V'} , {$set:{codigo:"FEDIB313"}})
db.averages.updateMany({title: 'Ecosistema'},  {$set:{codigo:"FMECO201"}})
db.averages.updateMany({title: 'Taller Principal III (PEG)'}, {$set:{codigo:"FETAP213"}})
db.averages.updateMany({title: 'Filosofía del Arte'}, {$set:{codigo:"CAFAR307"}})
db.averages.updateMany({title: 'Diseño Artístico Digital I'}, {$set:{codigo:"FEDAD315"}})
db.averages.updateMany({title: 'Semiótica del Arte'}, {$set:{codigo:"CASAR301"}})
db.averages.updateMany({title: 'Taller Principal I (PEG)'}, {$set:{codigo:"FETAP113"}})
db.averages.updateMany({title: 'Fundamentos Visuales I'}, {$set:{codigo:"CAFVI109"}})
db.averages.updateMany({title: 'Historia del Arte VI'}, {$set:{codigo:"CAHAR305"}})
db.averages.updateMany({title: 'Métodos de Estudios Superiores'}, {$set:{codigo:"FGMES105"}})
db.averages.updateMany({title: 'Cerámica II'},  {$set:{codigo:"FECER413"}})
db.averages.updateMany({title: 'Fundamentos Visuales III'}, {$set:{codigo:"CAFVI203"}})
db.averages.updateMany({title: 'Psicología del Arte'}, {$set:{codigo:"CAPÀR209"}})
db.averages.updateMany({title: 'Proyectos Artísticos Culturales'}, {$set:{codigo:"CAPAC501"}})
db.averages.updateMany({title: 'Historia del Arte IV'}, {$set:{codigo:"CAHAR401"}})
db.averages.updateMany({title: 'Taller Principal VII (PEG)'}, {$set:{codigo:"FETAP405"}})
db.averages.updateMany({title: 'Seminario Artístico Digital II'}, {$set:{codigo:"FESAD505"}})
db.averages.updateMany({title: 'Arte Virtual'}, {$set:{codigo:"FEAVI409"}})
db.averages.updateMany({title: 'Crítica del Arte'}, {$set:{codigo:"CACRA403"}})
db.averages.updateMany({title: 'Taller Principal IX (PEG)'}, {$set:{codigo:"FETAP503"}})
db.averages.updateMany({title: 'Dibujo VII'},  {$set:{codigo:"FEDIB407"}})
db.averages.updateMany({title: 'Investigación Artística I'}, {$set:{codigo:"FEINA411"}})
db.averages.updateMany({title: 'Práctica Pre Profesional I'}, {$set:{codigo:"FEPPP511"}})
db.averages.updateMany({title: 'Taller de Conservación y Restauración II'}, {$set:{codigo:"FETCR509"}})




db.averages.updateMany({title: 'Elementos Estéticos I'},{$set:{codigo:"AFPEE115"}})
db.averages.updateMany({title: 'Comunicación I'},{$set:{codigo:"ABCOM101"}})
db.averages.updateMany({title: 'Perspectiva'}, {$set:{codigo:"AFPPE113"}})
db.averages.updateMany({title: 'Dibujo I'}, {$set:{codigo:"AFPDI107"}})
db.averages.updateMany({title: 'Dibujo III'}, {$set:{codigo:"AFPDI211"}})
db.averages.updateMany({title: 'Sociedad I'}, {$set:{codigo:"ABSOC203"}})
db.averages.updateMany({title: 'Pintura I'}, {$set:{codigo:"AFPPI109"}})
db.averages.updateMany({title: 'Didáctica de las Artes II'},{$set:{codigo:"AEDIA205"}})
db.averages.updateMany({title: 'Escultura I'}, {$set:{codigo:"AFPES111"}})
db.averages.updateMany({title: 'Morfología Visual'},{$set:{"AFPMV11codigo:7AFPMV117"}})
db.averages.updateMany({title: 'Investigación II'},{$set:{codigo:"AEINV503"}})
db.averages.updateMany({title: 'Historia del Arte I'},{$set:{codigo:"AFPHA217"}})
db.averages.updateMany({title: 'Taller Regional I'},{$set:{codigo:"AFPTR315"}})
db.averages.updateMany({title: 'Grabado III'}, {$set:{codigo:"AFPGR411"}})
db.averages.updateMany({title: 'Retrato I'}, {$set:{codigo:"AFPTE417"}})
db.averages.updateMany({title: 'Historia del Arte III'},{$set:{codigo:"AFPHA319"}})
db.averages.updateMany({title: 'Diseño Artístico'},{$set:{codigo:"AFPDA219"}})
db.averages.updateMany({title: 'Teatro I'}, {$set:{codigo:"AFPRE409"}})
db.averages.updateMany({title: 'Danza I'}, {$set:{codigo:"AFPDA507"}})
db.averages.updateMany({title: 'Tutoría y Práctica Pedagógica I'},{$set:{codigo:"AFPPP419"}})
db.averages.updateMany({title: 'Didáctica de las Artes IV'},{$set:{codigo:"AEDIA307"}})
db.averages.updateMany({title: 'Filosofía II'},{$set:{codigo:"ABFIL403"}})
db.averages.updateMany({title: 'Cerámica I'}, {$set:{codigo:"AFPCE413"}})
db.averages.updateMany({title: 'Integración Artística II'},{$set:{codigo:"AFPIA412"}})
db.averages.updateMany({title: 'Psicología II'},{$set:{codigo:"AEPSI311"}})
db.averages.updateMany({title: 'Escultura III'},{$set:{codigo:"AFPES215"}})
db.averages.updateMany({title: 'Dibujo V'}, {$set:{codigo:"AFPDI313"}})
db.averages.updateMany({title: 'Teoría de la Educación II'},{$set:{codigo:"AETED309"}})
db.averages.updateMany({title: 'Música II'}, {$set:{codigo:"AFPMU415"}})
db.averages.updateMany({title: 'Métodos de Estudios Superiores'},{$set:{codigo:"ABMES103"}})
db.averages.updateMany({title: 'Matemática I'},{$set:{codigo:"ABMAT201"}})
db.averages.updateMany({title: 'Pintura III'}, {$set:{codigo:"AFPPI213"}})
db.averages.updateMany({title: 'Currículo Tecnología y Gestión IV'},{$set:{codigo:"AECTG501"}})
db.averages.updateMany({title: 'Currículo Tecnología y Gestión II'},{$set:{codigo:"AECTG405"}})
db.averages.updateMany({title: 'Tutoría y Práctica Pedagógica III'},{$set:{codigo:"AFPPP509"}})
db.averages.updateMany({title: 'Grabado I'},{$set:{codigo:"AFPGR317"}})





